from __future__ import annotations

from typing import Protocol

from expense_tracker.domain.models import Expense


class ExpenseRepository(Protocol):
    def save(self, expense: Expense) -> None: ...
    def list_all(self) -> list[Expense]: ...
    def find_by_id(self, expense_id: str) -> Expense | None: ...
    def delete(self, expense_id: str) -> bool: ...
